require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - bin/*
    - db/*schema.rb
    - db/**/*_create_versions.rb
    - spec/spec_helper.rb
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - app/models/orders/order.rb
RSpec/DescribeClass:
  Exclude:
    - spec/acceptance/*
RSpec/ExampleLength:
  Exclude:
    - spec/acceptance/*
Style/Documentation:
  Enabled: false
Style/HashSyntax:
  EnforcedShorthandSyntax: never
Style/StringLiterals:
  Exclude:
    - Rakefile
    - config.ru
    - config/application.rb
    - config/boot.rb
    - config/puma.rb
    - spec/rails_helper.rb