require:
  - rubocop-rails
  - rubocop-rspec
Style/Documentation:
  Enabled: false
AllCops:
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - app/models/orders/order.rb
RSpec/DescribeClass:
  Exclude:
    - spec/acceptance/*
RSpec/ExampleLength:
  Exclude:
    - spec/acceptance/*