inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - bin/*
    - app/controllers/graphql_controller.rb
    - app/graphql/sources/active_record_object.rb
    - config/puma.rb
    - config/initializers/devise.rb
    - db/*schema.rb
    - db/**/*_create_versions.rb
    - spec/spec_helper.rb
    - spec/rails_helper.rb
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - app/models/orders/order.rb
RSpec/DescribeClass:
  Exclude:
    - spec/acceptance/*
RSpec/ExampleLength:
  Exclude:
    - spec/acceptance/*
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Exclude:
    - app/controllers/users/registrations_controller.rb
    - app/controllers/users/sessions_controller.rb
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalStdStream:
  Exclude:
    - config/environments/production.rb
    -
Style/HashSyntax:
  EnforcedShorthandSyntax: never
Style/StringLiterals:
  Exclude:
    - Rakefile
    - config.ru
    - config/application.rb
    - config/boot.rb
    - spec/rails_helper.rb