default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres_username" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "postgres_password" } %>

development:
  primary:
    <<: *default
    database: ecommerce_modular_development
  inventory:
    <<: *default
    database: ecommerce_modular_inventory_development
    migrations_paths: db/inventory_migrate
  orders:
    <<: *default
    database: ecommerce_modular_orders_development
    migrations_paths: db/orders_migrate
  payments:
    <<: *default
    database: ecommerce_modular_payments_development
    migrations_paths: db/payments_migrate

test:
  primary:
    <<: *default
    database: ecommerce_modular_test
  inventory:
    <<: *default
    database: ecommerce_modular_inventory_test
    migrations_paths: db/inventory_migrate
  orders:
    <<: *default
    database: ecommerce_modular_orders_test
    migrations_paths: db/orders_migrate
  payments:
    <<: *default
    database: ecommerce_modular_payments_test
    migrations_paths: db/payments_migrate

production:
  primary:
    <<: *default
    database: ecommerce_modular_production
    inventory:
      <<: *default
      database: ecommerce_modular_inventory_production
      migrations_paths: db/inventory_migrate
    orders:
      <<: *default
      database: ecommerce_modular_orders_production
      migrations_paths: db/orders_migrate
    payments:
      <<: *default
      database: ecommerce_modular_payments_production
      migrations_paths: db/payments_migrate
